import { Inter } from "next/font/google";
// import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
// import Content from "../components/Content";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Image Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
