import { Inter } from "next/font/google";
// import type { Metadata } from "next";
// import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Image Gallery",
  description: "Generated by create next app",
};

export default function CharactersLayout({ children }) {
  return (
    <>
      <div>{children}</div>
    </>
  );
}
